# DOTS - demo

## Load packages

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd

from src.dots import DOTS
from src.eval_utils import perform_eval, read_json

## Load data

In [2]:
data = pd.read_csv("./data/samples.csv")
data_lagged = pd.read_csv("./data/samples_lagged.csv")

display(data.head())
display(data_lagged.head())

         X1        X2        X3
0 -0.056156  0.016618  0.350070
1  0.459504  0.313831  0.208192
2 -0.418800 -0.143756 -0.028618
3 -0.275246  0.279802  0.192227
4 -0.140182 -0.376564  0.679268

    X1_lag0   X2_lag0   X3_lag0   X1_lag1   X2_lag1   X3_lag1
0  0.459504  0.313831  0.208192 -0.056156  0.016618  0.350070
1 -0.418800 -0.143756 -0.028618  0.459504  0.313831  0.208192
2 -0.275246  0.279802  0.192227 -0.418800 -0.143756 -0.028618
3 -0.140182 -0.376564  0.679268 -0.275246  0.279802  0.192227
4 -0.087579 -0.057275  0.081553 -0.140182 -0.376564  0.679268

## DOTS training

In [6]:
nb_vars = data.shape[1]
nb_nodes = data_lagged.shape[1]
nb_lags = nb_nodes // nb_vars

dots = DOTS(nb_nodes)

adj = dots.fit(data_lagged.to_numpy(), nb_timesteps=nb_lags, nb_variables=nb_vars)

df_adj = pd.DataFrame(adj, columns=data_lagged.columns, index=data_lagged.columns)

MLP number of parameters 5269510

Training Epoch:  22%|██▏       | 661/3000 [00:20<01:12, 32.30it/s, Epoch Loss=0.801]

Early stoping at epoch 661
Best model at epoch 360 with loss 0.7574052214622498

Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.31it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.78it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.72it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.47it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.79it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.76it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.50it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.78it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.42it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.22it/s]
Nodes ordered : 100%|██████████| 5/5 [00:00<00:00, 18.59it/s]
Loading required package: nlme
This is mgcv 1.8-40. For overview type 'help("mgcv-package")'.

## Evaluation

In [7]:
graphs_true = read_json("./data/graphs_true.json")
perform_eval(graphs_true, df_adj, data.columns)

   s_precision  s_recall  s_f1  w_precision  w_recall  w_f1
0          1.0  0.666667   0.8          1.0  0.666667   0.8

## Comparing predicted graph to the ground truth

In [8]:
df_adj_true = pd.read_csv("./data/adjmat.csv")
df_adj_true.index = df_adj_true.columns
display(df_adj_true)
display(df_adj)

         X1_lag0  X2_lag0  X3_lag0  X1_lag1  X2_lag1  X3_lag1
X1_lag0      0.0      0.0      0.0      0.0      0.0      0.0
X2_lag0      0.0      0.0      0.0      0.0      0.0      0.0
X3_lag0      0.0      0.0      0.0      0.0      0.0      0.0
X1_lag1      0.0      0.0      0.0      0.0      0.0      0.0
X2_lag1      0.0      0.0      1.0      0.0      0.0      0.0
X3_lag1      1.0      0.0      1.0      0.0      0.0      0.0

         X1_lag0  X2_lag0  X3_lag0  X1_lag1  X2_lag1  X3_lag1
X1_lag0        0        0        0        0        0        0
X2_lag0        0        0        0        0        0        0
X3_lag0        0        0        0        0        0        0
X1_lag1        0        0        0        0        0        0
X2_lag1        0        0        1        0        0        0
X3_lag1        0        0        1        0        0        0